# Generated by Django 5.1.1 on 2024-10-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image_file",
            field=models.ImageField(
                default="images/users/user.jpeg",
                upload_to="images/users",
                verbose_name="image",
            ),
        ),
    ]
