# Generated by Django 5.1.1 on 2024-10-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_image_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verify",
            field=models.BooleanField(default=False, verbose_name="is verify"),
        ),
    ]
