# Generated by Django 5.1.1 on 2024-10-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_otp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="created_date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="updated_date",
        ),
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="created at"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="updated at"
            ),
        ),
    ]
